<template>
  <div id="first" class="section align-items-center prevent-select">
    <div class="bg-filter" style="z-index: -1">
      <div></div>
    </div>
    <div class="bg-bottom" style="z-index: -1">
      <div></div>
    </div>
    <img src="../assets/flowerstop.png" class="top-leaf absolute top-0" />
    <div class="flex align-items-center gap-5 flex-column content text-center">
      <p class="date">Samedi<br /> 29 juin 2024</p>
      <p class="location">Domaine des Coteaux d'Or<br /> Porte des Pierres Dorées</p>
      <Countdown></Countdown>
      <div class="flex gap-3 align-items-center">
        <p class="font-bold">Cliquez ici <i class="pi pi-arrow-right ml-2 vertical-align-middle" ></i></p>
        <a href="#rsvp"><Button label="RSVP" icon="pi pi-send" raised rounded/></a>
      </div>
    </div>
    <div class="hidden md:flex flex-column mt-5 opacity-80">
      <a href="#story">
        <p style="height: 35px;line-height:35px;" class="font-bold mb-3 text-xl">Voir les détails</p>
        <div style="height: 49px;" class="slide-fwd-top relative flex justify-content-center">
          <svg width="66" height="15" viewBox="0 0 66 15" fill="none" class="absolute bottom-0">
            <path opacity="0.8" fill-rule="evenodd" clip-rule="evenodd" d="M30.294 14.1a10 10 0 005.882 0l27.905-8.586a2.5 2.5 0 00-1.47-4.779L36.176 8.87a10 10 0 01-5.882 0L3.86.735a2.5 2.5 0 00-1.47 4.78L30.293 14.1z" fill="black"></path>
          </svg>
        </div>
      </a>
    </div>
  </div>
</template>

<script setup lang="ts">
import Countdown from './Countdown.vue'
</script>

<style>
.slide-fwd-top {
  animation: slide-fwd-top 4s ease-out 1.5s infinite normal none running;
}

.top-leaf {
  width: 70%
}

.content {
  margin-top: 8rem;
}

.bg-filter {
  top: 50%;
  left: 50%;
  width: 100%;
  height: 100%;
  position: absolute;
  transform: translateX(-50%) translateY(-50%);
  pointer-events: none;
}

.bg-filter:first-child {
  width: 100%;
  height: 100%;
  position: absolute;
  background-size: cover;
  background-image: url('../assets/bg-back.webp');
  background-repeat: no-repeat;
  background-position-x: center;
  background-position-y: center;
}

.bg-bottom>div {
  width: 100%;
  height: 100%;
  position: absolute;
  background-size: contain;
  background-image: url('../assets/bg.png');
  background-repeat: no-repeat;
  background-position: center bottom;
}

.bg-bottom {
  left: 50%;
  width: 100%;
  bottom: 0;
  height: auto;
  position: absolute;
  transform: translateX(-50%);
  pointer-events: none;
}

.bg-bottom:after {
  width: 0;
  content: ' ';
  display: block;
  padding-top: 54.72826086956522%;
}

.date {
  font-family: bartleen;
  font-weight: 400;
  white-space: pre-wrap;
  text-transform: none;
  letter-spacing: 0em;
  line-height: 1.25;
  font-size: 2rem;
}

.location {
  font-family: bartleen;
  font-weight: 400;
  font-size: 1.625rem;
  line-height: 1.25;
  text-transform: none;
  letter-spacing: 0em;
}

/* ----------------------------------------------
 * Generated by Animista on 2023-10-5 13:55:59
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-fwd-top
 * ----------------------------------------
 */
@-webkit-keyframes slide-fwd-top {

  0%,
  20%,
  50%,
  80%,
  100% {
    transform: translateY(0px);
  }

  40% {
    transform: translateY(-23px);
  }

  60% {
    transform: translateY(-23px);
  }
}

@media only screen and (max-width: 600px) {
  .content {
    margin-top: 6rem;
  }
}
</style>